build:
  image: node:$$NODE_VERSION
  environment:
    CXX: g++-4.8
  commands:
    - apt update
    - apt install -y g++-4.8
    - npm install
    - npm run build
    - npm run lint
    - npm run test

matrix:
  NODE_VERSION:
    - 5
    - 6

publish:
  ecr:
    region: us-east-1
    repo: 210246326331.dkr.ecr.us-east-1.amazonaws.com/mweb_reddit_mobile
    # Image gets tagged with the branch's name.
    tag: $$BRANCH
    file: Dockerfile.staging

# These plugins are triggered after a build failure/success.
#notify:
#  slack:
#    webhook_url: $$CI_SLACK_WEBHOOK_URL
#    channel: ci-notifications
